apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: {{.KUBE_NAMESPACE}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        env: {{.KUBE_NAMESPACE}}
    spec:
      containers:
      - name: api
        image: "{{.IMAGE_TAG}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "0.05Gi"
            cpu: "0.008"
        env:
        - name: MONGODB_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: cluster
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: password
        - name: MONGODB_DB
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: db
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 60
          httpGet:
            port: 8081
            path: /health
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          httpGet:
            port: 8081
            path: /health
      - name: csp
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: 
        resources:
          requests:
            memory: "0"
            cpu: "0"
        env:
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: csp
              key: instance-connection-name
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: csp-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      imagePullSecrets:
      - name: api-registry-deploy-token
      volumes:
        - name: csp-credentials
          secret:
            secretName: csp-credentials
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
