apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: {{.KUBE_NAMESPACE}}
  labels:
    app: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: “true”
spec:
  rules:
  - host: "*.flavour101.com"
    http:
      paths:
        - path: /api/
          backend:
            serviceName: api
            servicePort: 80
  tls:
  - secretName: tls-cert-prod
    hosts:
    - "*.flavour101.com"