apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: {{.KUBE_NAMESPACE}}
  labels:
    app: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "*.flavour101.com"
    http:
      paths:
        - path: /api/
          backend:
            serviceName: api
            servicePort: 80
