apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{.KUBE_NAMESPACE}}
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP